version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: wiegehtki/zoneminder:latest
        restart: unless-stopped
        ports:
            - 443:443/tcp
            - 9000:9000/tcp
        network_mode: "bridge"
        privileged: true
        environment:
            - TZ=Europe/Berlin
            - SHMEM=50%
            - PUID=99
            - PGID=100
            - INSTALL_HOOK=1
            - INSTALL_FACE=1
            - INSTALL_TINY_YOLO3=1
            - INSTALL_YOLO3=1
            - INSTALL_TINY_YOLO4=1
            - INSTALL_YOLO4=1
            - MULTI_PORT_START=0
            - MULTI_PORT_END=0
        volumes:
            - config:/config:rw
            - data:/var/cache/zoneminder:rw
volumes:
    config:
    data:
